name: CI Workflow
on:
  push:
    branches:
      - develop

env:
  APP_ENV: "development"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_LEVEL: "unit"
    environment: lololo
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
        id: step1

      - name: Test
        uses: ./.github/actions/tests
        with:
          python-version: "3.12"

      - name: Show tests result
        env:
          TEST_LEVEL: "integration"
        run: |
          echo "The result was ${{steps.test.outputs.app-status}}"
          echo "The level test is $TEST_LEVEL"
      - name: Show secret
        run: echo "Password is ${{secrets.DB_PASSWORD}}"
