name: CI Workflow
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: "1"
      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
        id: step1
      - name: Test
        if: steps.step1.outputs.status == 'success'
        run: |
          echo "El resultado del paso anterior fue ${{ steps.step1.outputs.status }}"
          echo "Running test ..."
