name: CI Workflow
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo "Installing dependencies ..."
          echo "status=success" >> $GITHUB_OUTPUT
        id: step1

      - name: Test
        if: steps.step1.outputs.status == 'success'
        run: |
          echo "El resultado del paso anterior fue ${{ steps.step1.outputs.status }}"
          echo "Running test ..."
