name: CI Workflow
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: python
        run: |
          print("Installing dependencies ...")
          print("Running tests ...")
