name: CI Workflow
on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          git init  
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
          git fetch origin ${{github.ref}} --depth=1
          git checkout FETCH_HEAD
      - name: Install dependencies
        run: |
          echo "Installing dependencies ..."
          echo "status=success" >> $GITHUB_OUTPUT
        id: step1

      - name: Test
        if: steps.step1.outputs.status == 'success'
        run: |
          echo "El resultado del paso anterior fue ${{ steps.step1.outputs.status }}"
          echo "Running test ..."
