name: AI Code Review

on:
  pull_request:
    types:
      - opened

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure UV and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: uv sync
      - name: Test
        id: run-tests
        run: uv run pytest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure UV and Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: uv sync
      - name: Run aplication
        run: uv run main.py
