name: CI Workflow
on:
  workflow_dispatch: {}
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build
        run: echo "Building the project ..."
