name: Hello World Worflow

on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello world"

  test:
    runs-on: ubuntu-latest
    needs: hello
    if: ${{success()}}
    steps:
      - name: Ejecucion test
        run: echo "Running test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{success()}}
    steps:
      - name: Deploy
        run: echo "Deploying application ..."
